version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: ekip_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: EkipReadDb
    ports:
      - '18800:5432'
    volumes:
      - postgres_data_final:/var/lib/postgresql/data
  mongo:
    image: mongo:latest
    container_name: ekip_mongo
    command: mongod --replSet rs0 --bind_ip_all --port 27017
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --port 27017 --eval 'try { rs.status() } catch(e) { rs.initiate({ _id: \"rs0\", members: [{ _id: 0, host: \"localhost:27017\" }] }) }'"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ekip_rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  redis:
    image: redis:alpine
    container_name: ekip_redis
    ports:
      - '16379:6379'
    command: redis-server --appendonly yes
volumes:
  postgres_data_final:
  mongo_data: