// <auto-generated />
using System;
using System.Collections.Generic;
using Ekip.Infrastructure.Persistence.PostgreSql.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ekip.Infrastructure.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    partial class PostgresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ekip.Domain.Entities.ReadModels.ChatRoomReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ChatRoomType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorRef")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastMessageDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastMessagePreview")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<Guid>>("Participants")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid>("RequestRef")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ChatRoomReads");
                });

            modelBuilder.Entity("Ekip.Domain.Entities.ReadModels.MessageReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatRoomRef")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReplyToMessageRef")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderRef")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MessageReads");
                });

            modelBuilder.Entity("Ekip.Domain.Entities.ReadModels.ProfileReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserRef")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserRef");

                    b.ToTable("ProfileReads");
                });

            modelBuilder.Entity("Ekip.Domain.Entities.ReadModels.RequestAssignmentReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("RequestRef")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderRef")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequestRef");

                    b.HasIndex("SenderRef");

                    b.ToTable("RequestAssignmentReads");
                });

            modelBuilder.Entity("Ekip.Domain.Entities.ReadModels.RequestReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorRef")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAutoAccept")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaximumRequiredAssignmnets")
                        .HasColumnType("integer");

                    b.Property<int>("MemberType")
                        .HasColumnType("integer");

                    b.Property<int?>("RepeatType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestFilters")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("RequestForbidDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequestType")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredMembers")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatorRef");

                    b.ToTable("RequestReads");
                });

            modelBuilder.Entity("Ekip.Domain.Entities.ReadModels.UserReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Gender")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProfileRef")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserReads");
                });

            modelBuilder.Entity("Ekip.Domain.Entities.ReadModels.ProfileReadModel", b =>
                {
                    b.HasOne("Ekip.Domain.Entities.ReadModels.UserReadModel", "User")
                        .WithMany()
                        .HasForeignKey("UserRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ekip.Domain.Entities.ReadModels.RequestAssignmentReadModel", b =>
                {
                    b.HasOne("Ekip.Domain.Entities.ReadModels.RequestReadModel", "Requests")
                        .WithMany("Assignments")
                        .HasForeignKey("RequestRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ekip.Domain.Entities.ReadModels.ProfileReadModel", "SenderProfile")
                        .WithMany("RequestAssignments")
                        .HasForeignKey("SenderRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requests");

                    b.Navigation("SenderProfile");
                });

            modelBuilder.Entity("Ekip.Domain.Entities.ReadModels.RequestReadModel", b =>
                {
                    b.HasOne("Ekip.Domain.Entities.ReadModels.ProfileReadModel", "Creator")
                        .WithMany("Requests")
                        .HasForeignKey("CreatorRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Ekip.Domain.Entities.ReadModels.ProfileReadModel", b =>
                {
                    b.Navigation("RequestAssignments");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Ekip.Domain.Entities.ReadModels.RequestReadModel", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
